services:
  - type: web
    name: healthcare-app
    runtime: docker
    repo: https://github.com/SivaSundar17/healthcare-appointment-system.git
    branch: main
    dockerfilePath: ./Dockerfile.all
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: postgresql://healthcare_user:0YXeJlTTYQSwFuIf6uau24tmqYSgKm54@dpg-d7uu4i77f7vs73d14b20-a/healthcare_xkpc
      - key: JWT_SECRET_KEY
        value: your-secret-key-here-change-this
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: 8080
